version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: board-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: boarddb
      MYSQL_USER: boarduser
      MYSQL_PASSWORD: boardpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
